export const DESK_CARDS_COUNT = 52;
export const HAND_CARDS_COUNT = 7;
export const HANDS_COUNT = 2;
export const HANDS_BUTTONS = [2, 3, 4, 5, 6, 7];
export const BACK = { name: 'back', value: 100 };
export const CARDS_WEIGHT = ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A'];
export const CARDS = {
  100: { name: 'back', value: -1 },
  0: { name: '2_of_clubs', value: 1 },
  1: { name: '2_of_diamonds', value: 1 },
  2: { name: '2_of_hearts', value: 1 },
  3: { name: '2_of_spades', value: 1 },
  4: { name: '3_of_clubs', value: 2 },
  5: { name: '3_of_diamonds', value: 2 },
  6: { name: '3_of_hearts', value: 2 },
  7: { name: '3_of_spades', value: 2 },
  8: { name: '4_of_clubs', value: 3 },
  9: { name: '4_of_diamonds', value: 3 },
  10: { name: '4_of_hearts', value: 3 },
  11: { name: '4_of_spades', value: 3 },
  12: { name: '5_of_clubs', value: 4 },
  13: { name: '5_of_diamonds', value: 4 },
  14: { name: '5_of_hearts', value: 4 },
  15: { name: '5_of_spades', value: 4 },
  16: { name: '6_of_clubs', value: 5 },
  17: { name: '6_of_diamonds', value: 5 },
  18: { name: '6_of_hearts', value: 5 },
  19: { name: '6_of_spades', value: 5 },
  20: { name: '7_of_clubs', value: 6 },
  21: { name: '7_of_diamonds', value: 6 },
  22: { name: '7_of_hearts', value: 6 },
  23: { name: '7_of_spades', value: 6 },
  24: { name: '8_of_clubs', value: 7 },
  25: { name: '8_of_diamonds', value: 7 },
  26: { name: '8_of_hearts', value: 7 },
  27: { name: '8_of_spades', value: 7 },
  28: { name: '9_of_clubs', value: 8 },
  29: { name: '9_of_diamonds', value: 8 },
  30: { name: '9_of_hearts', value: 8 },
  31: { name: '9_of_spades', value: 8 },
  32: { name: '10_of_clubs', value: 9 },
  33: { name: '10_of_diamonds', value: 9 },
  34: { name: '10_of_hearts', value: 9 },
  35: { name: '10_of_spades', value: 9 },
  36: { name: 'j_of_clubs', value: 10 },
  37: { name: 'j_of_diamonds', value: 10 },
  38: { name: 'j_of_hearts', value: 10 },
  39: { name: 'j_of_spades', value: 10 },
  40: { name: 'q_of_clubs', value: 11 },
  41: { name: 'q_of_diamonds', value: 11 },
  42: { name: 'q_of_hearts', value: 11 },
  43: { name: 'q_of_spades', value: 11 },
  44: { name: 'k_of_clubs', value: 12 },
  45: { name: 'k_of_diamonds', value: 12 },
  46: { name: 'k_of_hearts', value: 12 },
  47: { name: 'k_of_spades', value: 12 },
  48: { name: 'a_of_clubs', value: 13 },
  49: { name: 'a_of_diamonds', value: 13 },
  50: { name: 'a_of_hearts', value: 13 },
  51: { name: 'a_of_spades', value: 13 },
};
